<?php
/**
 * Appointment: Настройки валидатора
 * File: validator.php
 * Version: 0.0.2
 * Author: Anton Kuleshov
 **/

return [
    'MESSAGES' => [
        'ACCEPTED' => 'Вы должны принять ":attribute".',
        'ACTIVE_URL' => 'Поле ":attribute" недействительный URL.',
        'AFTER' => 'Поле ":attribute" должно быть датой после :date.',
        'AFTER_OR_EQUAL' => 'Поле ":attribute" должно быть датой равной или после :date.',
        'ALPHA' => 'Поле ":attribute" может содержать только буквы.',
        'ALPHA_DASH' => 'Поле ":attribute" может содержать только буквы, цифры и дефис.',
        'ALPHA_NUM' => 'Поле ":attribute" может содержать только буквы и цифры.',
        'ARRAY' => 'Поле ":attribute" должно быть массивом.',
        'BEFORE' => 'Поле ":attribute" должно быть датой перед :date.',
        'BEFORE_OR_EQUAL' => 'Поле ":attribute" должно быть датой равной или до :date.',
        'BETWEEN.NUMERIC' => 'Поле ":attribute" должно быть между :min и :max.',
        'BETWEEN.FILE' => 'Размер ":attribute" должен быть от :min до :max Килобайт.',
        'BETWEEN.STRING' => 'Длина ":attribute" должна быть от :min до :max символов.',
        'BETWEEN.ARRAY' => 'Поле ":attribute" должно содержать :min - :max элементов.',
        'BOOLEAN' => 'The ":attribute" field must be true or false.',
        'CONFIRMED' => 'Поле ":attribute" не совпадает с подтверждением.',
        'DATE' => 'Поле ":attribute" не является датой.',
        'DATE_FORMAT' => 'Поле ":attribute" не соответствует формату :format.',
        'DIFFERENT' => 'Поля ":attribute" и :other должны различаться.',
        'DIGITS' => 'Длина цифрового поля ":attribute" должна быть :digits.',
        'DIGITS_BETWEEN' => 'Длина цифрового поля ":attribute" должна быть между :min и :max.',
        'DIMENSIONS' => 'Изображение ":attribute" имеет недопустимые размеры.',
        'DISTINCT' => 'Поле ":attribute" имеет повторяющееся значение.',
        'EMAIL' => 'Поле ":attribute" имеет ошибочный формат.',
        'EXISTS' => 'Выбранное значение для ":attribute" уже существует.',
        'FILE' => 'Поле ":attribute" должно быть файлом.',
        'FILLED' => 'Поле ":attribute" должно иметь значение.',
        'IMAGE' => 'Поле ":attribute" должно быть изображением.',
        'IN' => 'Выбранное значение для ":attribute" ошибочно.',
        'IN_ARRAY' => 'Поле ":attribute" не существует в ":other".',
        'INTEGER' => 'Поле ":attribute" должно быть целым числом.',
        'IP' => 'Поле ":attribute" должно быть действительным IP-адресом.',
        'IPV4' => 'Поле ":attribute" должно быть действительным IPv4-адресом.',
        'IPV6' => 'Поле ":attribute" должно быть действительным IPv6-адресом.',
        'JSON' => 'Поле ":attribute" должно быть строкой в формате JSON.',
        'MAX.NUMERIC' => 'Поле ":attribute" должно быть не больше :max.',
        'VALIDATION.MAX.NUMERIC' => 'Поле ":attribute" должно быть не больше :max.',
        'MAX.FILE' => 'Поле ":attribute" должно быть не больше :max Килобайт.',
        'MAX.STRING' => 'Поле ":attribute" должно быть не длиннее :max символов.',
        'MAX.ARRAY' => 'Поле ":attribute" должно содержать не более :max элементов.',
        'MIMES' => 'Поле ":attribute" должно быть файлом одного из типов: :values.',
        'MIMETYPES' => 'Поле ":attribute" должно иметь одно из расширений: :values.',
        'MIN.NUMERIC' => 'Поле ":attribute" должно быть не менее :min.',
        'VALIDATION.MIN.NUMERIC' => 'Поле ":attribute" должно быть не менее :min.',
        'MIN.FILE' => 'Поле ":attribute" должно быть не менее :min Килобайт.',
        'MIN.STRING' => 'Поле ":attribute" должно быть не короче :min символов.',
        'MIN.ARRAY' => 'Поле ":attribute" должно содержать не менее :min элементов.',
        'NOT_IN' => 'Выбранное значение для ":attribute" ошибочно.',
        'NUMERIC' => 'Поле ":attribute" должно быть числом.',
        'PRESENT' => 'Поле ":attribute" должно присутствовать.',
        'REGEX' => 'Поле ":attribute" имеет ошибочный формат.',
        'REQUIRED' => 'Поле ":attribute" обязательно для заполнения.',
        'REQUIRED_IF' => 'Поле ":attribute" обязательно для заполнения, когда :other равно :value.',
        'REQUIRED_UNLESS' => 'Поле ":attribute" является обязательным, если поле ":other" равно :values.',
        'REQUIRED_WITH' => 'Поле ":attribute" обязательно для заполнения, когда :values указано.',
        'REQUIRED_WITH_ALL' => 'Поле ":attribute" является обязательным, когда есть :values.',
        'REQUIRED_WITHOUT' => 'Поле ":attribute" обязательно для заполнения, когда :values не указано.',
        'REQUIRED_WITHOUT_ALL' => 'Поле ":attribute" является обязательным, если нет ни одного из значений :values.',
        'SAME' => 'Значение ":attribute" должно совпадать с :other.',
        'SIZE.NUMERIC' => 'Поле ":attribute" должно быть :size.',
        'SIZE.FILE' => 'Поле ":attribute" должно быть :size Килобайт.',
        'SIZE.STRING' => 'Поле ":attribute" должно быть длиной :size символов.',
        'SIZE.ARRAY' => 'Количество элементов в поле ":attribute" должно быть :size.',
        'STRING' => 'Поле ":attribute" должно быть строкой.',
        'TIMEZONE' => 'Поле ":attribute" должно быть временной зоной.',
        'UNIQUE' => 'Такое значение поля ":attribute" уже существует.',
        'UPLOADED' => 'Поле ":attribute": не удалось загрузить файл.',
        'URL' => 'Поле ":attribute" имеет ошибочный формат.'
    ]
];